version: '3.8'

services:
  reddit-bot:
    image: ghcr.io/vincenthopf/reddit-agent:latest
    container_name: reddit-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs